name: "Build and publish project"
on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: build
        run: ./gradlew build
      - name: Get commit hash
        id: vars
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GITHUB_SHA_SHORT }}
          files: build/libs/*.jar
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          make_latest: ${{ github.ref == 'refs/heads/main' }}
          target_commitish: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
