name: "Check Code Style"
on: [push, workflow_dispatch]
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle Pull Request Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run code style check
        uses: nikitasavinov/checkstyle-action@master
        with:
          reporter: 'github-pr-check'
          checkstyle_config: google_checks.xml
          level: error
          filter_mode: added
          fail_on_error: true
          tool_name: 'Checkstyle-Everything'
